In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('CGWB_data_wide.csv')

In [3]:
df.head()

,Unnamed: 0,STATE,DISTRICT,LAT,LON,SITE_TYPE,WLCODE,05/01/1996,08/01/1996,11/01/1996,...,11/01/2014,01/01/2015,05/01/2015,08/01/2015,11/01/2015,01/01/2016,05/01/2016,08/01/2016,11/01/2016,01/01/2017
0,1,TG,Adilabad,19.087222,78.336111,Dug Well,W26026,NaN,NaN,NaN,...,2.10,2.36,3.86,0.91,2.06,2.32,3.26,1.56,1.71,2.86
1,2,TG,Adilabad,19.087778,78.401111,Dug Well,W26027,NaN,NaN,NaN,...,3.93,4.03,7.33,2.39,4.30,2.46,NaN,2.48,1.49,6.03
2,3,TG,Adilabad,19.170556,77.933611,Dug Well,W26044,NaN,NaN,NaN,...,3.62,3.47,11.72,3.84,6.82,3.32,11.72,1.28,1.41,11.72
3,4,TG,Adilabad,19.176667,78.103611,Dug Well,W26046,NaN,NaN,NaN,...,4.30,NaN,6.30,1.55,5.18,5.21,7.50,2.97,4.03,6.18
4,5,TG,Adilabad,19.160278,78.634444,Dug Well,W26040,NaN,NaN,NaN,...,3.67,3.30,4.78,2.77,3.40,3.06,8.65,3.34,5.98,6.75

In [6]:
df.shape

(28076, 90)

In [4]:
df.isnull().sum()

Unnamed: 0        0
STATE             0
DISTRICT          1
LAT               1
LON               0
              ...
01/01/2016    12179
05/01/2016    14878
08/01/2016    13166
11/01/2016    12997
01/01/2017    20761
Length: 91, dtype: int64

In [5]:
# Step 1: Drop columns (dates) with more than 85% missing values
df = df.dropna(thresh=df.shape[0]*0.15, axis=1)

# Step 2: Identify date columns (from column index 7 onward in your dataset)
date_cols = df.columns[7:]

# Step 3: Forward + Backward fill (good for short gaps)
df[date_cols] = df[date_cols].ffill(axis=1).bfill(axis=1)

# Step 4: Interpolation across dates (linear filling between known points)
df[date_cols] = df[date_cols].interpolate(method="linear", axis=1)

# Step 5: Fill any remaining NaN values with the row’s median (seasonal fallback)
df[date_cols] = df[date_cols].T.fillna(df[date_cols].median(axis=1)).T

# Check how many null values are left
print("Remaining missing values:", df.isnull().sum().sum())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8448\4085381489.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[date_cols] = df[date_cols].ffill(axis=1).bfill(axis=1)

Remaining missing values: 584

In [7]:
df.shape

(28076, 90)

In [8]:
df.isnull().sum()

Unnamed: 0    0
STATE         0
DISTRICT      1
LAT           1
LON           0
             ..
01/01/2016    0
05/01/2016    0
08/01/2016    0
11/01/2016    0
01/01/2017    0
Length: 90, dtype: int64

In [9]:
df.head()

,Unnamed: 0,STATE,DISTRICT,LAT,LON,SITE_TYPE,WLCODE,05/01/1996,08/01/1996,11/01/1996,...,11/01/2014,01/01/2015,05/01/2015,08/01/2015,11/01/2015,01/01/2016,05/01/2016,08/01/2016,11/01/2016,01/01/2017
0,1,TG,Adilabad,19.087222,78.336111,Dug Well,W26026,2.32,2.32,2.32,...,2.10,2.36,3.86,0.91,2.06,2.32,3.26,1.56,1.71,2.86
1,2,TG,Adilabad,19.087778,78.401111,Dug Well,W26027,6.03,6.03,6.03,...,3.93,4.03,7.33,2.39,4.30,2.46,2.46,2.48,1.49,6.03
2,3,TG,Adilabad,19.170556,77.933611,Dug Well,W26044,7.18,7.18,7.18,...,3.62,3.47,11.72,3.84,6.82,3.32,11.72,1.28,1.41,11.72
3,4,TG,Adilabad,19.176667,78.103611,Dug Well,W26046,4.30,4.30,4.30,...,4.30,4.30,6.30,1.55,5.18,5.21,7.50,2.97,4.03,6.18
4,5,TG,Adilabad,19.160278,78.634444,Dug Well,W26040,8.60,8.60,8.60,...,3.67,3.30,4.78,2.77,3.40,3.06,8.65,3.34,5.98,6.75

In [11]:
df.drop(['Unnamed: 0'],axis=1,inplace = True)

In [12]:
df.shape

(28076, 89)

In [13]:
df.to_csv("CGWB_data_cleaned.csv", index=False)
print("Cleaned dataset saved as CGWB_data_cleaned.csv")

Cleaned dataset saved as CGWB_data_cleaned.csv